---
title: "ksts"
author: "Xiaomeng Yuan"
date: "8/26/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(surveillance)
library(animation)
```

```{r}
row.names(kmap2)
kmap2@data[["NAME_1"]]
```
create observed matrix
```{r}
observed <- obs1[ , 2:18]
summary(observed)
colnames(observed)

kobserved <- observed[, c(1, 2, 3, 4, 5, 6, 7, 10, 8, 9, 11, 12, 13, 14, 15, 16, 17)]
colnames(kobserved)

kobs <- kobserved
colnames(kobs)<- c(0:16)

# create a matrix with all -1 replaced with 0
kobs1 <- replace(kobs, kobs==-1, 0)
```



create a t*i population matrix
```{r}
pdata <-t(pdata)
prow <- as.numeric(pdata[2,])
pmatrix <- matrix(rep(prow, each = 60), nrow = 60)
pdata[1,]
colnames(pmatrix)
```


```{r}
ksts <- sts(observed=kobs, start=c(2020,1), frequency = 60, neighbourhood=korder, map=kmap2, population=pmatrix)

# one useful error message when I first attemp to construct a sts object: Error in validObject(.Object) : invalid class “sts” object: 1: 'map' is incomplete; ensure that all(colnames(observed) %in% row.names(map)) invalid class “sts” object: 2: 'colnames(neighbourhood)' differ from 'colnames(observed)'

# create a sts object with all -1 observation replaced by 0
ksts1 <- sts(observed=kobs1, start=c(2020,1), frequency = 60, neighbourhood=korder, map=kmap2, population=pmatrix)
```

See help(stsplot).

Plot daily new cases 
```{r}
plot(ksts, type = observed ~ time)
```

plot incidence per 100000 person
```{r}
#see stsplot_space {surveillance} for help info
# how is person-time defined in computing incidence using stsplot() here?

plot(ksts, type = observed ~ unit,
population = population(ksts)/100000, 
labels = list(font = 2), colorkey = list(space = "right"), sp.layout = layout.scalebar(ksts@map,
corner = c(0.05, 0.05), scale = 50, labels = c("0", "50 km"), height = 0.03))
# not sure if the 0-50 km scale is right
```

```{r}
# use a vector of regional populations to plot incidence
# see tsplot_space {surveillance}

plot(ksts, type = observed ~ unit,
population = prow/100000, 
labels = list(font = 2), colorkey = list(space = "right"), sp.layout = layout.scalebar(ksts@map,
corner = c(0.05, 0.05), scale = 50, labels = c("0", "50 km"), height = 0.03))
```

```{r}
plot(ksts, units = which(colSums(observed(ksts)) > 0))
```

```{r}
animation::saveHTML(
animate(ksts, tps = 1:60, total.args = list()),
title = paste("Evolution of the COVID-19 epidemic in the South Korea",
"region, 2020"), ani.width = 500, ani.height = 600)

# somehow this animate() function cannot deal with observations = -1, it worked after I replaced all -1 to 0 in the obervation matrix. 
animation::saveHTML(
animate(ksts1, tps = 1:60, total.args = list()),
title = paste("Evolution of the COVID-19 epidemic in the South Korea",
"region, 2020"), ani.width = 500, ani.height = 600)
```

HHH4 Modeling
```{r}
kctrl0_basic <- list(
  end = list(f = ~1, 
  offset = population(ksts)), 
  ar = list(f = ~1),
  ne = list(f = ~1, weights = neighbourhood(ksts) == 1),
  family = "NegBin1") # non-convergent

kfit0_basic <- hhh4(stsObj = ksts,control = kctrl0_basic)
summary(kfit0_basic, idx2Exp = TRUE, amplitudeShift = TRUE, maxEV = TRUE)

#confint(kfit0_basic, parm = "overdisp")
```

```{r}
kctrl1_basic <- list(
  end = list(f = ~1, 
  offset = population(ksts)/sum(prow)), 
  ar = list(f = ~1),
  ne = list(f = ~1, weights = neighbourhood(ksts) == 1),
  family = "Poisson")

kfit1_basic <- hhh4(stsObj = ksts,control = kctrl1_basic)
summary(kfit1_basic, idx2Exp = TRUE, amplitudeShift = TRUE, maxEV = TRUE)

AIC(kfit1_basic)
```

```{r}
districts2plot <- which(colSums(observed(ksts)) > 20)
plot(kfit1_basic, type = "fitted", units = districts2plot, hide0s = TRUE)

```

```{r}
kctrl2_basic <- list(
  end = list(f = ~1, 
  offset = population(ksts)), 
  ar = list(f = ~1),
  ne = list(f = ~1, weights = neighbourhood(ksts) == 1),
  family = "NegBinM")

kfit2_basic <- hhh4(stsObj = ksts,control = kctrl2_basic)
summary(kfit2_basic, idx2Exp = TRUE, amplitudeShift = TRUE, maxEV = TRUE)
```

